const client=supabase.createClient(window.FF_CONFIG.supabaseUrl,window.FF_CONFIG.supabaseKey);
const app=document.getElementById('app');
let session=JSON.parse(localStorage.getItem('ff_session')||'null');
let user=session?.user||null;
let jobs=[];
let tailors=[];
let filter='all';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const statusName=s=>({pending:'PENDING',received:'RECEIVED',in_progress:'IN PROGRESS',ready:'READY',delivered:'DELIVERED',cancelled:'CANCELLED'}[s]||s);
const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-';
const api=async(action,payload={})=>{const {data,error}=await client.functions.invoke('tailor-api',{body:{action,token:session?.token||'',...payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data};
const logout=()=>{session=null;user=null;jobs=[];localStorage.removeItem('ff_session');login()};
const counts=a=>['pending','in_progress','ready','delivered'].map(s=>a.filter(j=>j.status===s).length);

function login(){
 app.innerHTML=`<div class="login"><div class="login-card"><div class="login-brand"><div class="brand-mark">FF</div><h2>FASHION FACTORY</h2><div class="muted">ALTERATION MANAGEMENT</div></div><div class="field"><label>LOGIN AS</label><select id="role"><option value="admin">Showroom / Admin</option><option value="tailor">Tailor</option></select></div><div class="field" style="margin-top:12px"><label>4-DIGIT PIN</label><input id="pin" class="pin" inputmode="numeric" maxlength="4" placeholder="••••" autocomplete="off"/></div><button class="primary" style="width:100%;margin-top:16px" id="go">LOGIN</button><div class="muted" style="text-align:center;margin-top:12px">Tailor PIN identifies the tailor automatically.</div></div></div>`;
 document.getElementById('go').onclick=async()=>{const role=document.getElementById('role').value,pin=document.getElementById('pin').value;const b=document.getElementById('go');b.disabled=true;b.textContent='Signing in…';try{const r=await api('login',{role,pin});session={token:r.token,user:r.user};user=r.user;localStorage.setItem('ff_session',JSON.stringify(session));await loadData();render()}catch(e){alert(e.message||'Login failed');b.disabled=false;b.textContent='LOGIN'}};
 document.getElementById('pin').onkeydown=e=>{if(e.key==='Enter')document.getElementById('go').click()};
}

function header(){return `<header class="topbar"><div class="toprow"><div class="brand"><div class="brand-mark">FF</div><div><div class="brand-name">FASHION FACTORY</div><div class="brand-sub">ALTERATION MANAGEMENT</div></div></div><button id="logout" class="secondary">Logout</button></div><div class="role">${user.role==='tailor'?'TAILOR VIEW':'SHOWROOM / ADMIN'} • ${esc(user.name)}</div></header>`}
function stats(a){const c=counts(a);return `<div class="stats"><div class="stat"><b>${c[0]}</b><span>Pending</span></div><div class="stat"><b>${c[1]}</b><span>In Progress</span></div><div class="stat"><b>${c[2]}</b><span>Ready</span></div><div class="stat"><b>${c[3]}</b><span>Delivered</span></div></div>`}
function jobData(j){return {id:j.id,number:j.alteration_no,bill:j.item_description||'',customer:j.customer?.name||'-',mobile:j.customer?.mobile||'',item:j.item_type,size:j.size||'-',tailor:j.tailor?.name||'',tailorId:j.assigned_tailor_id||'',due:j.due_date, status:j.status, details:j.alteration_details||'', measurements:j.measurements?.raw||JSON.stringify(j.measurements||{}), special:j.special_instructions||''}}
function card(raw){const j=jobData(raw);const isTailor=user.role==='tailor';const next=j.status==='pending'?'in_progress':j.status==='in_progress'?'ready':j.status==='ready'?'delivered':null;const label=j.status==='pending'?'START WORK':j.status==='in_progress'?'MARK READY':j.status==='ready'?'MARK DELIVERED':'COMPLETED';return `<article class="job"><div class="job-head"><div><div class="job-no">ALT-${String(j.number).padStart(4,'0')}</div><div class="bill">${j.bill?'Bill No. '+esc(j.bill):'Bill not entered'}</div></div><span class="status ${j.status}">${statusName(j.status)}</span></div><div class="customer">${esc(j.customer)}</div><div class="item">${esc(j.item)} • Size ${esc(j.size)}</div><div class="meta"><span class="chip">Tailor: ${esc(j.tailor||'Not Assigned')}</span><span class="chip">Due: ${fmt(j.due)}</span></div><div class="muted">${esc(j.details)}</div><details style="margin-top:10px"><summary>View measurements & details</summary><div class="detail-box"><b>Measurements</b><br>${esc(j.measurements||'-')}<br><br><b>Instructions</b><br>${esc(j.special||'-')}<br><br><b>Mobile</b><br>${esc(j.mobile||'-')}</div></details><div class="actions" style="margin-top:12px">${!isTailor?`<button class="secondary" data-assign="${j.id}">${j.tailor?'Reassign Tailor':'Assign Tailor'}</button>`:''}${next?`<button class="primary" data-next="${j.id}" data-status="${next}">${label}</button>`:''}</div></article>`}
function list(){const q=(document.getElementById('search')?.value||'').toLowerCase();return jobs.filter(j=>(filter==='all'||j.status===filter)).filter(j=>{const x=jobData(j);return [x.id,x.number,x.bill,x.customer,x.mobile,x.item,x.tailor].join(' ').toLowerCase().includes(q)}).map(card).join('')||'<div class="empty">No alterations found.</div>'}
async function loadData(){const r=await api('list_jobs');jobs=r.jobs||[];if(user.role==='admin'){const t=await api('tailors');tailors=t.tailors||[]}}
function dashboard(){return `${header()}<main class="page"><div class="hero-row"><div><div class="title">${user.role==='tailor'?'Hi, '+esc(user.name)+' 👋':'Fashion Factory'}</div><div class="muted">${user.role==='tailor'?'Your assigned alteration jobs':'Today’s alteration control'}</div></div>${user.role==='admin'?'<button class="primary" id="new">＋ New Alteration</button>':''}</div>${stats(jobs)}<input id="search" class="search" placeholder="Search customer, mobile, bill or alteration no..."/><div class="filters"><button class="filter active" data-f="all">All</button>${['pending','in_progress','ready','delivered'].map(s=>`<button class="filter" data-f="${s}">${statusName(s)}</button>`).join('')}</div><section id="list">${list()}</section></main><nav class="bottom-nav">${user.role==='admin'?'<button class="nav-btn" id="report">Payment Report</button>':''}</nav>`}
async function form(){if(!tailors.length){const r=await api('tailors');tailors=r.tailors||[]}app.innerHTML=`${header()}<main class="page"><div class="hero-row"><div><div class="title">New Alteration</div><div class="muted">Create job and assign tailor</div></div></div><form class="form-card" id="form"><div class="form-grid"><div class="field"><label>Customer Name *</label><input name="customer" required autofocus></div><div class="field"><label>Mobile</label><input name="mobile" inputmode="numeric"></div><div class="field"><label>Bill Number</label><input name="bill"></div><div class="field"><label>Item *</label><select name="item"><option>Kurti</option><option>Kurti Set</option><option>Jeans</option><option>Top</option><option>Pant</option><option>Jeans Cutting</option><option>Other</option></select></div><div class="field"><label>Size</label><input name="size" placeholder="S / M / L / 32"></div><div class="field"><label>Tailor</label><select name="tailorId"><option value="">Not Assigned</option>${tailors.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label>Due Date *</label><input name="due" type="date" required value="${new Date().toISOString().slice(0,10)}"></div><div class="field full"><label>Alteration Details *</label><textarea name="details" required placeholder="Example: Sleeve short 1 inch + waist fitting"></textarea></div><div class="field full"><label>Measurements</label><textarea name="measurements" placeholder="Sleeve 16, Shoulder 14, Waist 32, Length 42"></textarea></div><div class="field full"><label>Special Instructions</label><textarea name="special" placeholder="Any special note for tailor"></textarea></div></div><div class="form-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Save Alteration</button></div></form></main>`;document.getElementById('cancel').onclick=render;document.getElementById('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),b=e.target.querySelector('button[type=submit]');b.disabled=true;b.textContent='Saving…';try{await api('create_job',{job:{customer:f.get('customer'),mobile:f.get('mobile'),bill:f.get('bill'),item_type:f.get('item'),size:f.get('size'),assigned_tailor_id:f.get('tailorId')||null,due_date:f.get('due'),alteration_details:f.get('details'),measurements:{raw:f.get('measurements')||''},special_instructions:f.get('special')||''}});await loadData();render()}catch(err){alert(err.message||'Could not save');b.disabled=false;b.textContent='Save Alteration'}}}
async function assign(jobId){const box=document.createElement('div');box.className='modal-backdrop';box.innerHTML=`<div class="modal"><h3>Assign Tailor</h3><div class="field"><label>TAILOR</label><select id="assignSelect">${tailors.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><div class="form-actions"><button class="secondary" id="cancelAssign">Cancel</button><button class="primary" id="saveAssign">Assign</button></div></div>`;document.body.appendChild(box);box.querySelector('#cancelAssign').onclick=()=>box.remove();box.querySelector('#saveAssign').onclick=async()=>{const b=box.querySelector('#saveAssign');b.disabled=true;try{await api('assign',{job_id:jobId,tailor_id:box.querySelector('#assignSelect').value});box.remove();await loadData();render()}catch(e){alert(e.message);b.disabled=false}}}
async function next(jobId,status){try{await api('status',{job_id:jobId,status});await loadData();render()}catch(e){alert(e.message||'Could not update status')}}
async function report(){const month=new Date().toISOString().slice(0,7);const r=await api('report',{month});app.innerHTML=`${header()}<main class="page"><div class="hero-row"><div><div class="title">Payment Report</div><div class="muted">Tailor-wise delivered pieces</div></div><button class="secondary" id="back">Back</button></div><div class="form-card"><div class="field"><label>MONTH</label><input id="month" type="month" value="${month}"></div><div id="reportRows" style="margin-top:14px">${reportRows(r.rows)}</div></div></main>`;document.getElementById('back').onclick=render;document.getElementById('month').onchange=async e=>{const x=await api('report',{month:e.target.value});document.getElementById('reportRows').innerHTML=reportRows(x.rows)}}
function reportRows(rows){const total=rows.reduce((a,r)=>a+r.amount,0),pieces=rows.reduce((a,r)=>a+r.pieces,0);return `${rows.map(r=>`<div class="job"><div class="job-head"><b>${esc(r.name)}</b><b>₹${r.amount.toFixed(0)}</b></div><div class="muted">${r.pieces} pieces</div></div>`).join('')||'<div class="empty">No delivered jobs for this month.</div>'}<div class="report-total"><b>Total Pieces</b><b>${pieces}</b><b>Total Payable ₹${total.toFixed(0)}</b></div>`}
function bind(){document.getElementById('logout')?.addEventListener('click',logout);document.getElementById('new')?.addEventListener('click',form);document.getElementById('report')?.addEventListener('click',report);document.getElementById('search')?.addEventListener('input',()=>document.getElementById('list').innerHTML=list());document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{filter=b.dataset.f;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('list').innerHTML=list();bind()});document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>next(b.dataset.next,b.dataset.status));document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>assign(b.dataset.assign))}
async function render(){if(!user)return login();try{if(!jobs.length)await loadData();app.innerHTML=dashboard();bind()}catch(e){if(String(e.message).toLowerCase().includes('session'))logout();else app.innerHTML=`<div class="login"><div class="login-card"><h2>Something went wrong</h2><p>${esc(e.message)}</p><button class="primary" onclick="location.reload()">Retry</button></div></div>`}}
render();
