const tailors=[{id:'t1',name:'Hiteshbhai'},{id:'t2',name:'Hardik'}];
const seed=[
{id:'ALT-0004',bill:'1024',customer:'Rina Patel',item:'Kurti Set',size:'M',tailor:'Hiteshbhai',tailorId:'t1',due:'2026-08-28',status:'pending',details:'Sleeve short 1 inch + waist fitting',measurements:'Sleeve 16, Shoulder 14, Waist 32, Length 42'},
{id:'ALT-0003',bill:'1027',customer:'Sanket Joshi',item:'Jeans',size:'32',tailor:'Hardik',tailorId:'t2',due:'2026-08-27',status:'in_progress',details:'Length alteration',measurements:'Length 40'},
{id:'ALT-0002',bill:'1029',customer:'Hema Benediction',item:'Jeans Cutting',size:'30',tailor:'Hiteshbhai',tailorId:'t1',due:'2026-08-26',status:'ready',details:'Waist fitting',measurements:'Waist 30, Length 39'},
{id:'ALT-0001',bill:'1018',customer:'Aditi Shah',item:'Kurti',size:'L',tailor:'Hardik',tailorId:'t2',due:'2026-08-25',status:'delivered',details:'Side fitting',measurements:'Waist 34'}];
let jobs=JSON.parse(localStorage.getItem('ff_jobs')||'null')||seed;
let user=JSON.parse(localStorage.getItem('ff_user')||'null');
let filter='all',view='jobs';
const app=document.getElementById('app');
const save=()=>localStorage.setItem('ff_jobs',JSON.stringify(jobs));
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const statusName=s=>({pending:'PENDING',in_progress:'IN PROGRESS',ready:'READY',delivered:'DELIVERED'}[s]||s);
const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-';
function counts(a){return ['pending','in_progress','ready','delivered'].map(s=>a.filter(j=>j.status===s).length)}
function login(){app.innerHTML=`<div class="login"><div class="login-card"><div class="login-brand"><div class="brand-mark">FF</div><h2>FASHION FACTORY</h2><div class="muted">ALTERATION MANAGEMENT</div></div><div class="field"><label>LOGIN AS</label><select id="role"><option value="admin">Showroom / Admin</option><option value="tailor">Tailor</option></select></div><div class="field" id="tf" style="display:none;margin-top:12px"><label>TAILOR</label><select id="tailor">${tailors.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><div class="field" style="margin-top:12px"><label>4-DIGIT PIN</label><input id="pin" class="pin" inputmode="numeric" maxlength="4" placeholder="••••" /></div><button class="primary" style="width:100%;margin-top:16px" id="go">LOGIN</button></div></div>`;document.getElementById('role').onchange=e=>document.getElementById('tf').style.display=e.target.value==='tailor'?'flex':'none';document.getElementById('go').onclick=()=>{const r=document.getElementById('role').value,p=document.getElementById('pin').value;if(r==='admin'&&p==='1234'){user={role:'admin',name:'Showroom Admin'}}else if(r==='tailor'&&['1111','2222'].includes(p)){const t=tailors.find(x=>x.id===document.getElementById('tailor').value);user={role:'tailor',name:t.name,tailorId:t.id}}else{return alert('Wrong PIN')};localStorage.setItem('ff_user',JSON.stringify(user));view='jobs';render()}}
function header(){return `<header class="topbar"><div class="toprow"><div class="brand"><div class="brand-mark">FF</div><div><div class="brand-name">FASHION FACTORY</div><div class="brand-sub">ALTERATION MANAGEMENT</div></div></div><button id="logout" class="secondary">Logout</button></div><div class="role">${user.role==='tailor'?'TAILOR VIEW':'SHOWROOM / ADMIN'}</div></header>`}
function stats(a){const c=counts(a);return `<div class="stats"><div class="stat"><b>${c[0]}</b><span>Pending</span></div><div class="stat"><b>${c[1]}</b><span>In Progress</span></div><div class="stat"><b>${c[2]}</b><span>Ready</span></div><div class="stat"><b>${c[3]}</b><span>Delivered</span></div></div>`}
function card(j){let button=user.role==='tailor'?(j.status==='pending'?'Start Work':j.status==='in_progress'?'Mark Ready':j.status==='ready'?'Mark Delivered':'Delivered'):(j.tailor?'Update Status':'Assign Tailor');return `<article class="job"><div class="job-head"><div><div class="job-no">${j.id}</div><div class="bill">Bill No. ${esc(j.bill)}</div></div><span class="status ${j.status}">${statusName(j.status)}</span></div><div class="customer">${esc(j.customer)}</div><div class="item">${esc(j.item)} • Size ${esc(j.size||'-')}</div><div class="meta"><span class="chip">Tailor: ${esc(j.tailor||'Not Assigned')}</span><span class="chip">Due: ${fmt(j.due)}</span></div><div class="muted">${esc(j.details)}</div><div class="actions" style="margin-top:12px"><button class="secondary" data-detail="${j.id}">View Details</button><button class="primary" data-next="${j.id}">${button}</button></div></article>`}
function list(){const mine=user.role==='tailor'?jobs.filter(j=>j.tailorId===user.tailorId):jobs;const q=(document.getElementById('search')?.value||'').toLowerCase();return mine.filter(j=>(filter==='all'||j.status===filter)&&[j.id,j.bill,j.customer,j.item,j.tailor].join(' ').toLowerCase().includes(q)).map(card).join('')||'<div class="empty">No alterations found.</div>'}
function dashboard(){const mine=user.role==='tailor'?jobs.filter(j=>j.tailorId===user.tailorId):jobs;return `${header()}<main class="page"><div class="hero-row"><div><div class="title">${user.role==='tailor'?'Hi, '+esc(user.name)+' 👋':'Fashion Factory'}</div><div class="muted">${user.role==='tailor'?'Your assigned alteration jobs':'Today’s alteration control'}</div></div>${user.role==='admin'?'<button class="primary" id="new">＋ New Alteration</button>':''}</div>${stats(mine)}<input id="search" class="search" placeholder="Search customer, bill or alteration no..."/><div class="filters"><button class="filter active" data-f="all">All</button>${['pending','in_progress','ready','delivered'].map(s=>`<button class="filter" data-f="${s}">${statusName(s)}</button>`).join('')}</div><section id="list">${list()}</section></main><nav class="bottom-nav">${user.role==='admin'?'<button class="nav-btn" id="report">Payment Report</button>':''}</nav>`}
function form(){app.innerHTML=`${header()}<main class="page"><div class="hero-row"><div><div class="title">New Alteration</div><div class="muted">Create job and assign tailor</div></div></div><form class="form-card" id="form"><div class="form-grid"><div class="field"><label>Customer Name *</label><input name="customer" required></div><div class="field"><label>Mobile</label><input name="mobile"></div><div class="field"><label>Bill Number</label><input name="bill"></div><div class="field"><label>Item *</label><select name="item"><option>Kurti</option><option>Kurti Set</option><option>Jeans</option><option>Top</option><option>Pant</option><option>Jeans Cutting</option><option>Other</option></select></div><div class="field"><label>Size</label><input name="size" placeholder="S / M / L / 32"></div><div class="field"><label>Tailor</label><select name="tailorId"><option value="">Not Assigned</option>${tailors.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><div class="field"><label>Due Date *</label><input name="due" type="date" required></div><div class="field full"><label>Alteration Details *</label><textarea name="details" required placeholder="Example: Sleeve short 1 inch + waist fitting"></textarea></div><div class="field full"><label>Measurements</label><textarea name="measurements" placeholder="Sleeve 16, Shoulder 14, Waist 32, Length 42"></textarea></div></div><div class="form-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Save Alteration</button></div></form></main>`;document.getElementById('cancel').onclick=()=>render();document.getElementById('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),t=tailors.find(x=>x.id===f.get('tailorId')),n=jobs.length+1;jobs.unshift({id:'ALT-'+String(n).padStart(4,'0'),bill:f.get('bill'),customer:f.get('customer'),item:f.get('item'),size:f.get('size'),tailor:t?.name||'',tailorId:t?.id||'',due:f.get('due'),status:'pending',details:f.get('details'),measurements:f.get('measurements')});save();render()}}
function report(){const by={};jobs.filter(j=>j.status==='delivered').forEach(j=>{const n=j.tailor||'Unassigned';by[n]??={pieces:0,amount:0};by[n].pieces++;by[n].amount+=j.item==='Jeans'?30:j.item.includes('Cutting')?50:20});app.innerHTML=`${header()}<main class="page"><div class="hero-row"><div><div class="title">Payment Report</div><div class="muted">Tailor-wise delivered pieces</div></div><button class="secondary" id="back">Back</button></div><div class="form-card"><h3>August 2026</h3>${Object.entries(by).map(([n,x])=>`<div class="job"><div class="job-head"><b>${esc(n)}</b><b>₹${x.amount}</b></div><div class="muted">${x.pieces} pieces</div></div>`).join('')||'<div class="empty">No delivered jobs yet.</div>'}</div></main>`;document.getElementById('back').onclick=render}
function next(id){const j=jobs.find(x=>x.id===id);if(!j)return;if(!j.tailor&&user.role==='admin')return alert('Assign a tailor first.');j.status={pending:'in_progress',in_progress:'ready',ready:'delivered',delivered:'delivered'}[j.status];save();render()}
function bind(){document.getElementById('logout')?.addEventListener('click',()=>{localStorage.removeItem('ff_user');user=null;login()});document.getElementById('new')?.addEventListener('click',form);document.getElementById('report')?.addEventListener('click',report);document.getElementById('search')?.addEventListener('input',()=>document.getElementById('list').innerHTML=list());document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{filter=b.dataset.f;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('list').innerHTML=list()});document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>next(b.dataset.next));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const j=jobs.find(x=>x.id===b.dataset.detail);alert(`${j.id}\n${j.customer}\n${j.item} • Size ${j.size||'-'}\nTailor: ${j.tailor||'Not Assigned'}\nDue: ${fmt(j.due)}\n\n${j.details}\n\nMeasurements: ${j.measurements||'-'}`)})}
function render(){if(!user)return login();if(view==='form')return form();if(view==='report')return report();app.innerHTML=dashboard();bind()}
render();