/* Runtime hardening for the three role dashboards. */
(function(){
  const escR=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const modal=(title,body,actions='')=>{document.getElementById('ffRuntimeModal')?.remove();const d=document.createElement('div');d.id='ffRuntimeModal';d.className='modal-backdrop';d.innerHTML='<div class="modal"><div class="job-head"><div class="title" style="font-size:20px">'+escR(title)+'</div><button class="secondary" id="ffClose">×</button></div><div style="margin-top:14px">'+body+'</div>'+actions+'</div>';document.body.appendChild(d);d.querySelector('#ffClose').onclick=()=>d.remove();d.addEventListener('click',e=>{if(e.target===d)d.remove()});return d};
  async function status(b){if(b.dataset.busy)return;b.dataset.busy='1';b.disabled=true;const old=b.textContent;b.textContent='Updating…';try{await api('update_status',{item_id:b.dataset.next,status:b.dataset.status});location.reload()}catch(e){alert(e.message||'Could not update status.');b.disabled=false;b.textContent=old;delete b.dataset.busy}}
  function jobFor(id){return (jobs||[]).find(j=>String(j.id)===String(id));}
  function timeline(id){const j=jobFor(id);if(!j)return modal('Timeline','Alteration item not found.');const a=j.alteration||{},c=a.customers||{};const rows=[['ALTERATION CREATED',a.created_at||j.created_at],['CURRENT STATUS',j.status],['LAST UPDATED',j.updated_at||j.delivered_at],['DELIVERY DATE',j.delivery_date],['TAILOR',j.tailor?.name||'Not assigned']].filter(x=>x[1]);return modal('Alteration Timeline','<div class="timeline-item"><b>'+escR(c.name||'Customer')+'</b><br><span class="muted">ALT-'+String(a.alteration_no||0).padStart(4,'0')+' • ITEM '+j.item_no+'</span></div>'+rows.map(x=>'<div class="timeline-item"><b>'+escR(x[0])+'</b><br><span class="muted">'+escR(x[1])+'</span></div>').join('')+'<div class="muted" style="margin-top:10px">This view uses the live alteration record. A full event-by-event audit trail requires a dedicated audit-log API.</div>');}
  function report(){const arr=jobs||[],qty=a=>arr.filter(a).reduce((n,j)=>n+Number(j.quantity||1),0),by={};arr.forEach(j=>{const n=j.tailor?.name||'Unassigned';by[n]=(by[n]||0)+Number(j.quantity||1)});const rows=Object.entries(by).map(([n,q])=>'<tr><td style="padding:8px 0">'+escR(n)+'</td><td style="text-align:right;padding:8px 0"><b>'+q+'</b></td></tr>').join('');return modal('Alteration Report','<div class="stat-grid" style="grid-template-columns:repeat(2,1fr)"><div class="stat-card"><span>TOTAL PCS</span><b>'+qty(()=>true)+'</b></div><div class="stat-card"><span>PENDING PCS</span><b>'+qty(j=>!['returned_to_showroom','delivered'].includes(j.status))+'</b></div><div class="stat-card"><span>READY / SHOWROOM</span><b>'+qty(j=>['ready','returned_to_showroom'].includes(j.status))+'</b></div><div class="stat-card"><span>DELIVERED</span><b>'+qty(j=>j.status==='delivered')+'</b></div></div><h3>TAILOR WORKLOAD</h3><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left">TAILOR</th><th style="text-align:right">PCS</th></tr></thead><tbody>'+rows+'</tbody></table>');}
  function printRows(arr){return arr.map(j=>'<div class="timeline-item"><b>'+escR(j.alteration?.customers?.name||'-')+'</b> • '+escR(j.item_type)+' × '+j.quantity+'<br><span class="muted">ALT-'+String(j.alteration?.alteration_no||0).padStart(4,'0')+' • '+escR(j.status)+'</span><button class="secondary small" data-runtime-print="'+escR(j.id)+'" style="float:right">🖨 PRINT</button></div>').join('')||'<div class="empty">No alterations found.</div>';}
  function reprintPicker(){const arr=jobs||[];const m=modal('Reprint Label','<input id="ffPrintSearch" class="search" placeholder="Search customer, bill or alteration…"><div id="ffPrintList" style="margin-top:10px">'+printRows(arr)+'</div>');const i=m.querySelector('#ffPrintSearch');i.oninput=()=>{const q=i.value.toLowerCase();m.querySelector('#ffPrintList').innerHTML=printRows(arr.filter(j=>[j.id,j.item_type,j.alteration?.alteration_no,j.alteration?.customers?.name,j.alteration?.item_description].join(' ').toLowerCase().includes(q)))};}
  function doPrint(id){const j=jobFor(id);if(!j)return;const item={bag_barcode:j.bag_barcode||j.bag_code||('B-'+j.id),product_barcode:j.product_barcode||j.product_code||('P-'+j.id)};if(typeof window.printLabels==='function')window.printLabels(j.alteration?.alteration_no||0,[item],j.alteration?.item_description||'',j.alteration?.customers?.name||'', [j]);else alert('Print module is not ready. Please refresh the app.');}
  function customerSearch(){const arr=jobs||[];const m=modal('Customer Search','<input id="ffCustSearch" class="search" placeholder="Customer / Mobile / Bill…"><div id="ffCustList" style="margin-top:10px">'+printRows(arr)+'</div>');const i=m.querySelector('#ffCustSearch');i.oninput=()=>{const q=i.value.toLowerCase();m.querySelector('#ffCustList').innerHTML=printRows(arr.filter(j=>[j.alteration?.customers?.name,j.alteration?.customers?.mobile,j.alteration?.item_description,j.alteration?.alteration_no].join(' ').toLowerCase().includes(q)))};}
  function controls(){modal('Admin Controls','<div class="timeline-item"><b>Dashboard</b><br><span class="muted">Role permissions and live alteration controls are active.</span></div><div class="timeline-item"><b>Default Tailor</b><br><span class="muted">Hiteshbhai is selected automatically when available.</span></div><div class="timeline-item"><b>Data Source</b><br><span class="muted">Live Supabase data through tailor-api.</span></div>');}
  window.customers=customerSearch;window.adminControls=controls;
  document.addEventListener('click',async e=>{
    const next=e.target.closest('[data-next]');
    if(next){e.preventDefault();e.stopImmediatePropagation();await status(next);return;}
    const hist=e.target.closest('[data-history]');
    if(hist){e.preventDefault();e.stopImmediatePropagation();timeline(hist.dataset.history);return;}
    const rp=e.target.closest('[data-runtime-print]');
    if(rp){e.preventDefault();e.stopPropagation();doPrint(rp.dataset.runtimePrint);return;}
    if(e.target.closest('#reportQuick')){e.preventDefault();e.stopImmediatePropagation();report();return;}
    if(e.target.closest('#reprintQuick')){e.preventDefault();e.stopImmediatePropagation();reprintPicker();return;}
  },true);
  const boot=()=>{if(!session?.token)return;const root=document.getElementById('app');if(root&&!document.querySelector('.dashboard-page')&&!document.querySelector('#newForm')&&!document.querySelector('.login-card')&&window.dashboard){try{root.innerHTML=window.dashboard()}catch(e){console.error(e)}}};
  window.addEventListener('load',()=>setTimeout(boot,50));
  const mo=new MutationObserver(()=>{if(session?.token&&document.querySelector('.page')&&!document.querySelector('.dashboard-page')&&!document.querySelector('#newForm')&&!document.querySelector('.login-card'))setTimeout(boot,0)});mo.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});
})();
